### ISSUE TITLE
'lag' when creating secret

### ISSUE THREAD

**Issue by dillonstreator** [osbytes/crypt.fyi#25]
There is a noticeable main-thread blocking lag during encryption since the switch to `@noble/ciphers` & `@noble/hashes` 88903e6290f494b00eaf3a2b04a52eae313aaa7d 79352d202b8f5f5604121b46e16d00d2cdf47765

Investigate root cause and a fix (possibility to use a worker thread)

**Comment by dillonstreator** [comment]
@paulmillr curious if you have any ideas/thoughts/suggestions around this. All good if not and again appreciate the work you've done on your libraries!

**Comment by paulmillr** [comment]
What’s “lag”? Pvkdf2 is supposed to be slow.

async method will not block main thread you’re using

**Comment by dillonstreator** [comment]
The duration of time that `Pvkdf2` takes is okay but there appears to be a main thread blocking operation at some point during the `pbkdf2Async` call. There is a consistent css keyframe render lag as seen here:

![2024-12-20 16 08 10](https://github.com/user-attachments/assets/53cc1334-5f88-4f7e-9e11-211168a65d6e)

```ts
import { gcm } from '@noble/ciphers/aes';
import { pbkdf2Async } from '@noble/hashes/pbkdf2';
import { sha256 } from '@noble/hashes/sha256';
import { randomBytes } from '@noble/hashes/utils';
import { concatBytes, utf8ToBytes } from '@noble/hashes/utils';
import { Buffer } from 'buffer';

const SALT_LENGTH = 16;
const IV_LENGTH = 12;
const KEY_LENGTH = 32;
const ITERATIONS = 2 ** 19;

export async function encrypt(content: string, password: string): Promise<string> {
  const salt = randomBytes(SALT_LENGTH);
  console.time('pbkdf2');
  const key = await pbkdf2Async(sha256, utf8ToBytes(password), salt, {
    c: ITERATIONS,
    dkLen: KEY_LENGTH,
  });
  console.timeEnd('pbkdf2');

  const iv = randomBytes(IV_LENGTH);
  console.time('gcm');
  const cipher = gcm(key, iv);
  const encrypted = cipher.encrypt(utf8ToBytes(content));
  console.timeEnd('gcm');

  const result = concatBytes(salt, iv, encrypted);
  return Buffer.from(result).toString('base64');
}
```

**Comment by dillonstreator** [comment]
I see there is an `asyncTick` option on `pbkdf2` and I played with lowering but seeing the same results
```ts
  asyncTick?: number; // Maximum time in ms for which async function can block execution
```
