### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by aniellocap** [osbytes/crypt.fyi#47]
I'm searching for a note app to secure some secrets and share them between my devices, I have found yours and I want to run it in my home lab server as a docker compose.

I see that you are already providing 2 Dockerfiles: one for the server and one for the web, but after building the 2 images, I can't start the app properly.

Can you also provide a docker-compose that is working?

My main issue is with the network configuration: the server container cannot reach the Redis container and the web container cannot reach the server container.

Thank you so much.

**Comment by dillonstreator** [comment]
Thank you for checking out the project and submitting this issue. Deployment of this project is slightly more complicated than with similar projects that combine the api server and web server while they compromise a bit on security (as the api server can see the decryption key). FWIW - the security benefits aren't much realized when hosting web and api on the same server but that's okay.

docker compose will only help with the first issue of 'the server container cannot reach the Redis container' while the second comes down to setting the correct environment variables when building and running the docker image (`VITE_API_URL` & `API_URL`) relative to your deployment configuration/environment.

When _building_ the `Dockerfile.web`, you'll need to set the `VITE_API_URL` to your lab servers address. This embeds the API URL that the web application will call.
When _running_ the built web image, you'll need to set the `API_URL` to your lab servers address. This configures the nginx Content-Security-Policy (CSP) header.

ex.
```sh
docker build -e VITE_API_URL=192.168.0.100:4321 -f ./Dockerfile.web -t crypt.fyi/web:latest .

docker run -e API_URL=192.168.0.100:4321 -p 8000:80 crypt.fyi/web:latest`
```

You'll want to swap out 192.168.0.100:4321 with the ip:port of where your local server is running and the port that the api server is listening on on that server.

If the server api url needs to be updated, you'll need to rebuild the web image with the updated `VITE_API_URL` and rerun the image with the updated `API_URL`.

Regarding the server not being able to connect to redis, you'll want to make sure that the network is the same for the api server and redis https://docs.docker.com/engine/network/tutorials/host/. The existing docker-compose.yml should handle the server<>redis connection. Is there a particular error you're seeing w/r/t the server not being able to connect to redis when running the existing docker-compose?

I can look into setting up a docker-compose that wires up web, api, and redis but ultimately the correct VITE_API_URL and API_URL will need to be set for the deployment environment in question and the environment will need to properly expose the web and api applications.

Please try rebuilding and running the web image with the changes and LMK if you're still seeing issues and I'll try to help resolve.

**Comment by aniellocap** [comment]
Hello.
Thank you so much. I was able to create the cointainers but at runtime I have this cors error:

Access to fetch at 'https://api.subdomain.domain.com/vault' from origin 'https://cryptoweb.subdomain.domain.com' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains the invalid value 'api.subdomain.domain.com'. 
Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

For the server container I have provided those env variable:
      CORS_ORIGIN: '*'
      NODE_ENV: production

K.R.
Aniello

**Comment by dillonstreator** [comment]
Thank you for the details! Seems like an issue with how the `Access-Control-Allow-Origin` header is being constructed here:
https://github.com/osbytes/crypt.fyi/blob/ee172e56e1bde1df25e8f8ab1b63516021410a77/packages/server/src/app.ts#L90-L102

I suppose there's some problematic assumptions being made. That code works locally and on https://crypt.fyi. Maybe there is an issue with the nested subdomains?
Can you confirm what the request/response headers are in the OPTIONS request when attempting to create a secret? i.e.
![image](https://github.com/user-attachments/assets/8f280d3a-061c-42e7-8bba-7afd51d9c683)
![image](https://github.com/user-attachments/assets/ce2b813b-7ae0-4ac8-b1a6-fc23b3e7aa94)
![image](https://github.com/user-attachments/assets/b810213d-734e-463c-ad76-c0044249003b)

Ultimately, whatever is provided to `CORS_ORIGIN` env should be directly set on `Access-Control-Allow-Origin`.. I can get a fix pushed up for this before EOD.

Thanks again for the report and helping triage!

**Comment by aniellocap** [comment]
Here you are:

**General**
Request URL: https://api.subdomain.domain.com/vault
Request Method: OPTIONS
Status Code: 200 OK

**Response Headers**
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,X-Client
Access-Control-Allow-Methods: GET,HEAD,POST,DELETE,OPTIONS
Access-Control-Allow-Origin: api.subdomain.domain.com
Content-Length: 0
Content-Security-Policy: frame-ancestors 'self'
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: same-origin
Date: Mon, 30 Dec 2024 16:41:17 GMT
Origin-Agent-Cluster: ?1
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Dns-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none

**Request Headers**
:authority: api.subdomain.domain.com
:method: OPTIONS
:path: /vault
:scheme: https 
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,it;q=0.8
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Origin: https://cryptoweb.subdomain.domain.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36

Tnx for investigating!

**Comment by dillonstreator** [comment]
Hmm your request header `Origin: https://cryptoweb.subdomain.domain.com/` looks exactly as expected 🤔
I'll get the fix up to directly set the the `CORS_ORIGIN` value on the response header

**Comment by dillonstreator** [comment]
Can you please confirm if this change works for you? https://github.com/osbytes/crypt.fyi/commit/a3fffb49529c1b73b71a7f7fe595ed9134afc555#diff-b4bf798ca8820447b50fa3dd7cb2ab33ba486b016686ce4f98d28cb3df65b0aeL97

**Comment by aniellocap** [comment]
no, I have the same issue.

The response headers are not changed.

I was expecting 
Access-Control-Allow-Origin: *

but it's still
Access-Control-Allow-Origin: api.subdomain.domain.com

K.R.
Aniello

**Comment by dillonstreator** [comment]
I was able to reproduce issues trying to spin up the service locally and tossed together a docker compose file https://github.com/osbytes/crypt.fyi/commit/09c30f8404553bb51e539abf67562b598abd0438

If you pull down the latest from `main`, you should be able to now run:
```sh
API_URL=https://api.subdomain.domain.com docker compose up --build
```

From here, it should just be a matter of ensuring your local network configuration routes to the correct address & port.

Please let me know how this works.

**Comment by aniellocap** [comment]
It works for me now.

Tnx!!

Happy new year.
